// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getFacilitiesByUserID = `-- name: GetFacilitiesByUserID :many
SELECT 
    id, 
    name, 
    ST_Y(coordinates::geometry)::float8 as lat, 
    ST_X(coordinates::geometry)::float8 as lng, 
    created_at
FROM facilities
WHERE user_id = $1
`

type GetFacilitiesByUserIDRow struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Lat       float64      `json:"lat"`
	Lng       float64      `json:"lng"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) GetFacilitiesByUserID(ctx context.Context, userID uuid.NullUUID) ([]GetFacilitiesByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getFacilitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFacilitiesByUserIDRow
	for rows.Next() {
		var i GetFacilitiesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lat,
			&i.Lng,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequirementsByFacility = `-- name: GetRequirementsByFacility :many
SELECT id, facility_id, required_chemical, minimum_purity, max_acceptable_distance_meters, created_at FROM buyer_requirements 
WHERE facility_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRequirementsByFacility(ctx context.Context, facilityID uuid.NullUUID) ([]BuyerRequirement, error) {
	rows, err := q.db.QueryContext(ctx, getRequirementsByFacility, facilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuyerRequirement
	for rows.Next() {
		var i BuyerRequirement
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.RequiredChemical,
			&i.MinimumPurity,
			&i.MaxAcceptableDistanceMeters,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsForUser = `-- name: GetTransactionsForUser :many
SELECT 
    t.id AS transaction_id,
    ws.primary_chemical,
    t.tonnage_exchanged,
    t.net_savings_estimated,
    t.status,
    t.created_at,
    f_gen.name AS generator_name,
    f_buy.name AS buyer_name
FROM transactions t
JOIN waste_streams ws ON t.waste_stream_id = ws.id
JOIN facilities f_gen ON ws.facility_id = f_gen.id
JOIN buyer_requirements br ON t.buyer_requirement_id = br.id
JOIN facilities f_buy ON br.facility_id = f_buy.id
WHERE f_gen.user_id = $1 OR f_buy.user_id = $1
ORDER BY t.created_at DESC
`

type GetTransactionsForUserRow struct {
	TransactionID       uuid.UUID      `json:"transaction_id"`
	PrimaryChemical     string         `json:"primary_chemical"`
	TonnageExchanged    int32          `json:"tonnage_exchanged"`
	NetSavingsEstimated string         `json:"net_savings_estimated"`
	Status              sql.NullString `json:"status"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	GeneratorName       string         `json:"generator_name"`
	BuyerName           string         `json:"buyer_name"`
}

func (q *Queries) GetTransactionsForUser(ctx context.Context, userID uuid.NullUUID) ([]GetTransactionsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsForUserRow
	for rows.Next() {
		var i GetTransactionsForUserRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.PrimaryChemical,
			&i.TonnageExchanged,
			&i.NetSavingsEstimated,
			&i.Status,
			&i.CreatedAt,
			&i.GeneratorName,
			&i.BuyerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWasteStreamsByFacility = `-- name: GetWasteStreamsByFacility :many
SELECT id, facility_id, primary_chemical, purity_percentage, tonnage_available, local_landfill_fee_per_ton, lab_report_url, created_at FROM waste_streams 
WHERE facility_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWasteStreamsByFacility(ctx context.Context, facilityID uuid.NullUUID) ([]WasteStream, error) {
	rows, err := q.db.QueryContext(ctx, getWasteStreamsByFacility, facilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WasteStream
	for rows.Next() {
		var i WasteStream
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.PrimaryChemical,
			&i.PurityPercentage,
			&i.TonnageAvailable,
			&i.LocalLandfillFeePerTon,
			&i.LabReportUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
