// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteBuyerRequirement = `-- name: DeleteBuyerRequirement :exec
DELETE FROM buyer_requirements
WHERE id = $1 AND facility_id = $2
`

type DeleteBuyerRequirementParams struct {
	ID         uuid.UUID     `json:"id"`
	FacilityID uuid.NullUUID `json:"facility_id"`
}

func (q *Queries) DeleteBuyerRequirement(ctx context.Context, arg DeleteBuyerRequirementParams) error {
	_, err := q.db.ExecContext(ctx, deleteBuyerRequirement, arg.ID, arg.FacilityID)
	return err
}

const deleteWasteStream = `-- name: DeleteWasteStream :exec

DELETE FROM waste_streams
WHERE id = $1 AND facility_id = $2
`

type DeleteWasteStreamParams struct {
	ID         uuid.UUID     `json:"id"`
	FacilityID uuid.NullUUID `json:"facility_id"`
}

// sql/queries/delete.sql
func (q *Queries) DeleteWasteStream(ctx context.Context, arg DeleteWasteStreamParams) error {
	_, err := q.db.ExecContext(ctx, deleteWasteStream, arg.ID, arg.FacilityID)
	return err
}
