// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facilities.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createFacility = `-- name: CreateFacility :one

INSERT INTO facilities (id, user_id, name, coordinates)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    -- We take Longitude ($3) and Latitude ($4), turn them into a geometric point, 
    -- set the spatial reference to 4326 (WGS 84 / GPS Standard), and cast to geography.
    ST_SetSRID(ST_MakePoint($3::float8, $4::float8), 4326)::geography
)
RETURNING id, user_id, name, 
          ST_Y(coordinates::geometry)::float8 as lat, 
          ST_X(coordinates::geometry)::float8 as lng, 
          created_at
`

type CreateFacilityParams struct {
	UserID  uuid.NullUUID `json:"user_id"`
	Name    string        `json:"name"`
	Column3 float64       `json:"column_3"`
	Column4 float64       `json:"column_4"`
}

type CreateFacilityRow struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	Name      string        `json:"name"`
	Lat       float64       `json:"lat"`
	Lng       float64       `json:"lng"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

// sql/queries/facilities.sql
// Instead of returning the raw binary geography data (which Go will struggle to read),
// we use PostGIS functions to extract the exact Lat/Lng floats back out.
func (q *Queries) CreateFacility(ctx context.Context, arg CreateFacilityParams) (CreateFacilityRow, error) {
	row := q.db.QueryRowContext(ctx, createFacility,
		arg.UserID,
		arg.Name,
		arg.Column3,
		arg.Column4,
	)
	var i CreateFacilityRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
	)
	return i, err
}
