// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getViableMatchesForFacility = `-- name: GetViableMatchesForFacility :many

SELECT 
    ws.id AS waste_stream_id,
    ws.primary_chemical,
    ws.tonnage_available,
    ws.local_landfill_fee_per_ton,
    br.id AS buyer_requirement_id,
    f_buyer.name AS buyer_name,
    -- Calculate the exact distance in meters over the Earth's curvature
    ST_Distance(f_generator.coordinates, f_buyer.coordinates)::float8 AS distance_meters
FROM waste_streams ws
JOIN facilities f_generator ON ws.facility_id = f_generator.id
JOIN buyer_requirements br ON ws.primary_chemical = br.required_chemical
JOIN facilities f_buyer ON br.facility_id = f_buyer.id
WHERE f_generator.id = $1
  AND ws.tonnage_available > 0
  AND ws.purity_percentage >= br.minimum_purity
  AND ST_DWithin(f_generator.coordinates, f_buyer.coordinates, br.max_acceptable_distance_meters)
`

type GetViableMatchesForFacilityRow struct {
	WasteStreamID          uuid.UUID `json:"waste_stream_id"`
	PrimaryChemical        string    `json:"primary_chemical"`
	TonnageAvailable       int32     `json:"tonnage_available"`
	LocalLandfillFeePerTon string    `json:"local_landfill_fee_per_ton"`
	BuyerRequirementID     uuid.UUID `json:"buyer_requirement_id"`
	BuyerName              string    `json:"buyer_name"`
	DistanceMeters         float64   `json:"distance_meters"`
}

// sql/queries/matches.sql
// The Chemical Gate: Exact string match
func (q *Queries) GetViableMatchesForFacility(ctx context.Context, id uuid.UUID) ([]GetViableMatchesForFacilityRow, error) {
	rows, err := q.db.QueryContext(ctx, getViableMatchesForFacility, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetViableMatchesForFacilityRow
	for rows.Next() {
		var i GetViableMatchesForFacilityRow
		if err := rows.Scan(
			&i.WasteStreamID,
			&i.PrimaryChemical,
			&i.TonnageAvailable,
			&i.LocalLandfillFeePerTon,
			&i.BuyerRequirementID,
			&i.BuyerName,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
