// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type BuyerRequirement struct {
	ID                          uuid.UUID     `json:"id"`
	FacilityID                  uuid.NullUUID `json:"facility_id"`
	RequiredChemical            string        `json:"required_chemical"`
	MinimumPurity               string        `json:"minimum_purity"`
	MaxAcceptableDistanceMeters int32         `json:"max_acceptable_distance_meters"`
	CreatedAt                   sql.NullTime  `json:"created_at"`
}

type Facility struct {
	ID          uuid.UUID     `json:"id"`
	UserID      uuid.NullUUID `json:"user_id"`
	Name        string        `json:"name"`
	Coordinates interface{}   `json:"coordinates"`
	CreatedAt   sql.NullTime  `json:"created_at"`
}

type User struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	Role         string       `json:"role"`
	CompanyName  string       `json:"company_name"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type WasteStream struct {
	ID                     uuid.UUID      `json:"id"`
	FacilityID             uuid.NullUUID  `json:"facility_id"`
	PrimaryChemical        string         `json:"primary_chemical"`
	PurityPercentage       string         `json:"purity_percentage"`
	TonnageAvailable       int32          `json:"tonnage_available"`
	LocalLandfillFeePerTon string         `json:"local_landfill_fee_per_ton"`
	LabReportUrl           sql.NullString `json:"lab_report_url"`
	CreatedAt              sql.NullTime   `json:"created_at"`
}
