// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requirements.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createBuyerRequirement = `-- name: CreateBuyerRequirement :one

INSERT INTO buyer_requirements (
    id, facility_id, required_chemical, minimum_purity, max_acceptable_distance_meters
)
VALUES (
    gen_random_uuid(), $1, $2, $3, $4
)
RETURNING id, facility_id, required_chemical, minimum_purity, max_acceptable_distance_meters, created_at
`

type CreateBuyerRequirementParams struct {
	FacilityID                  uuid.NullUUID `json:"facility_id"`
	RequiredChemical            string        `json:"required_chemical"`
	MinimumPurity               string        `json:"minimum_purity"`
	MaxAcceptableDistanceMeters int32         `json:"max_acceptable_distance_meters"`
}

// sql/queries/requirements.sql
func (q *Queries) CreateBuyerRequirement(ctx context.Context, arg CreateBuyerRequirementParams) (BuyerRequirement, error) {
	row := q.db.QueryRowContext(ctx, createBuyerRequirement,
		arg.FacilityID,
		arg.RequiredChemical,
		arg.MinimumPurity,
		arg.MaxAcceptableDistanceMeters,
	)
	var i BuyerRequirement
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.RequiredChemical,
		&i.MinimumPurity,
		&i.MaxAcceptableDistanceMeters,
		&i.CreatedAt,
	)
	return i, err
}
