// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const executeMatchTransaction = `-- name: ExecuteMatchTransaction :one

WITH updated_waste AS (
    -- Step A: Attempt to deduct the tonnage
    UPDATE waste_streams
    SET tonnage_available = tonnage_available - $1
    WHERE id = $2 AND tonnage_available >= $1
    RETURNING id
)
INSERT INTO transactions (
    id, waste_stream_id, buyer_requirement_id, tonnage_exchanged, 
    freight_cost_estimated, net_savings_estimated
)
SELECT 
    gen_random_uuid(), $2, $3, $1, $4, $5
WHERE EXISTS (SELECT 1 FROM updated_waste)
RETURNING id, waste_stream_id, buyer_requirement_id, tonnage_exchanged, freight_cost_estimated, net_savings_estimated, status, created_at
`

type ExecuteMatchTransactionParams struct {
	TonnageExchanged     int32     `json:"tonnage_exchanged"`
	WasteStreamID        uuid.UUID `json:"waste_stream_id"`
	BuyerRequirementID   uuid.UUID `json:"buyer_requirement_id"`
	FreightCostEstimated string    `json:"freight_cost_estimated"`
	NetSavingsEstimated  string    `json:"net_savings_estimated"`
}

// sql/queries/transactions.sql
// Step B: Only if Step A succeeds, create the ledger entry
func (q *Queries) ExecuteMatchTransaction(ctx context.Context, arg ExecuteMatchTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, executeMatchTransaction,
		arg.TonnageExchanged,
		arg.WasteStreamID,
		arg.BuyerRequirementID,
		arg.FreightCostEstimated,
		arg.NetSavingsEstimated,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WasteStreamID,
		&i.BuyerRequirementID,
		&i.TonnageExchanged,
		&i.FreightCostEstimated,
		&i.NetSavingsEstimated,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
