// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: waste.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createWasteStream = `-- name: CreateWasteStream :one

INSERT INTO waste_streams (
    id, facility_id, primary_chemical, purity_percentage, 
    tonnage_available, local_landfill_fee_per_ton, lab_report_url
)
VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6
)
RETURNING id, facility_id, primary_chemical, purity_percentage, tonnage_available, local_landfill_fee_per_ton, lab_report_url, created_at
`

type CreateWasteStreamParams struct {
	FacilityID             uuid.NullUUID  `json:"facility_id"`
	PrimaryChemical        string         `json:"primary_chemical"`
	PurityPercentage       string         `json:"purity_percentage"`
	TonnageAvailable       int32          `json:"tonnage_available"`
	LocalLandfillFeePerTon string         `json:"local_landfill_fee_per_ton"`
	LabReportUrl           sql.NullString `json:"lab_report_url"`
}

// sql/queries/waste.sql
func (q *Queries) CreateWasteStream(ctx context.Context, arg CreateWasteStreamParams) (WasteStream, error) {
	row := q.db.QueryRowContext(ctx, createWasteStream,
		arg.FacilityID,
		arg.PrimaryChemical,
		arg.PurityPercentage,
		arg.TonnageAvailable,
		arg.LocalLandfillFeePerTon,
		arg.LabReportUrl,
	)
	var i WasteStream
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.PrimaryChemical,
		&i.PurityPercentage,
		&i.TonnageAvailable,
		&i.LocalLandfillFeePerTon,
		&i.LabReportUrl,
		&i.CreatedAt,
	)
	return i, err
}
